from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Callable


class PlaylistIngestionError(RuntimeError):
    """Raised when YT Music does not provide a usable playlist payload."""


def _artists(v: Any) -> str:
    if isinstance(v, list):
        names: list[str] = []
        for item in v:
            name = item.get("name") if isinstance(item, dict) else item
            text = str(name or "").strip()
            if text:
                names.append(text)
        return ", ".join(names)
    return str(v or "").strip()


def _duration(v: Any) -> int | None:
    if v is None:
        return None
    try:
        if isinstance(v, (int, float)):
            return int(round(float(v) * 1000))
        text = str(v).strip()
        if ":" in text:
            parts = [float(x) for x in text.split(":")]
            seconds = 0.0
            for part in parts:
                seconds = seconds * 60.0 + part
            return int(round(seconds * 1000))
        return int(round(float(text) * 1000))
    except (TypeError, ValueError):
        return None


def normalize_item(item: dict[str, Any], position: int) -> dict[str, Any]:
    """Normalize one playlist item without querying or calculating play/view counts."""
    video_id = item.get("videoId") or item.get("video_id")
    artists = _artists(item.get("artists") or item.get("artist")) or "Unknown Artist"
    album = item.get("album")
    if isinstance(album, dict):
        album = album.get("name")
    duration = item.get("duration_seconds")
    if duration is None:
        duration = item.get("duration")
    return {
        "video_id": str(video_id).strip() if video_id else None,
        "url": f"https://music.youtube.com/watch?v={video_id}" if video_id else None,
        "title": str(item.get("title") or "Untitled").strip(),
        "artist": artists,
        "album": str(album).strip() if album else None,
        "duration_ms": _duration(duration),
        "playlist_position": int(position),
        "available": item.get("isAvailable", True) is not False,
        "raw": item,
        "raw_json": json.dumps(item, ensure_ascii=False, sort_keys=True, default=str),
    }


class PlaylistClient:
    """YT Music API client used only for the one-time playlist snapshot."""

    def __init__(self, auth_file: str | Path | None = None, *, require_auth: bool = True):
        self.auth_file = Path(auth_file) if auth_file else None
        self.require_auth = bool(require_auth)
        self._api: Any = None

    def _client(self):
        if self._api is None:
            if self.auth_file and not self.auth_file.exists():
                raise PlaylistIngestionError(
                    f"YT Music authentication file not found: {self.auth_file}. "
                    "Run 'python scripts/setup_ytmusic_auth.py --output browser.json' "
                    "and set playlist.ytmusic_auth_file accordingly."
                )
            try:
                from ytmusicapi import YTMusic
            except ImportError as exc:
                raise PlaylistIngestionError(
                    "ytmusicapi is not installed. Install requirements.txt before playlist ingestion."
                ) from exc
            if self.auth_file:
                self._api = YTMusic(str(self.auth_file))
            else:
                if self.require_auth:
                    raise PlaylistIngestionError(
                        "YT Music authentication is required for this project. "
                        "Set playlist.ytmusic_auth_file to browser.json/oauth.json generated by ytmusicapi."
                    )
                self._api = YTMusic()
        return self._api

    @property
    def api(self):
        return self._client()

    def fetch_complete(self, playlist_id: str) -> dict[str, Any]:
        """Fetch the complete playlist once and return the API payload unchanged."""
        try:
            payload = self.api.get_playlist(
                playlist_id,
                limit=None,
                related=False,
                suggestions_limit=0,
            )
        except KeyError as exc:
            # ytmusicapi expects playlist contents at a known renderer path. A missing
            # 'contents' key commonly means YouTube did not return a playlist page that
            # the current authenticated/unauthenticated client can parse.
            if str(exc).strip("\"'") == "contents":
                mode = "authenticated" if self.auth_file else "unauthenticated"
                raise PlaylistIngestionError(
                    "YT Music returned no playlist contents for this client. "
                    f"The request was {mode}. This can occur for private/unlisted or auth-required playlists, "
                    "a stale browser session, a consent/bot challenge, or a YT Music response-shape change. "
                    "Use a fresh ytmusicapi browser.json (or OAuth file) and retry."
                ) from exc
            raise PlaylistIngestionError(f"ytmusicapi playlist parsing failed: {exc}") from exc
        except Exception as exc:
            raise PlaylistIngestionError(f"ytmusicapi playlist fetch failed: {type(exc).__name__}: {exc}") from exc
        if not isinstance(payload, dict):
            raise PlaylistIngestionError(
                f"ytmusicapi returned an unexpected playlist payload type: {type(payload).__name__}"
            )
        tracks = payload.get("tracks")
        if not isinstance(tracks, list):
            raise PlaylistIngestionError(
                "ytmusicapi returned no usable 'tracks' list for the playlist. "
                "Verify the playlist ID and YT Music authentication session."
            )
        return payload


def ingest_tracks(
    playlist_id: str,
    auth_file: str | Path | None = None,
    *,
    require_auth: bool = True,
    progress: Callable[[int, int, dict[str, Any]], None] | None = None,
):
    """Read and normalize the complete playlist once; no per-track API lookups occur."""
    client = PlaylistClient(auth_file, require_auth=require_auth)
    playlist = client.fetch_complete(playlist_id)
    raw_tracks = playlist.get("tracks") or []
    tracks = [normalize_item(item, index) for index, item in enumerate(raw_tracks, 1)]
    if progress:
        total = len(tracks)
        for index, track in enumerate(tracks, 1):
            progress(index, total, track)
    return playlist, tracks, client
